<?php

namespace Tests\Unit\Models;

use DateTime;
use Tests\TestCase;
use App\Models\People;
use App\Models\Country;
use App\Models\State;
use Illuminate\Support\Str;
use Illuminate\Foundation\Testing\RefreshDatabase;

class PeopleTest extends TestCase
{
    use RefreshDatabase;

    private $model;

    public function setUp() : void
    {
        parent::setUp();

        $this->model = People::create([
            'first_name' => 'Jaimito Alfonso',
            'last_name' => 'Hernandez',
            'document_type' => 'V',
            'document_id' => '23458706',
            'sex' => 'M',
            'email' => 'algo@mail.com',
            'birthday_at' => now(),
            'country_id' => Country::factory()->create()->id,
            'state_id' => State::factory()->create()->id
        ]);

    }

    /** @test */
    public function it_validate_that_model_uuid_has_been_autogenerated()
    {
        $this->assertNotNull($this->model->id);
        $this->assertTrue(Str::isUuid($this->model->id));
    }

    /** @test */
    public function it_validate_that_birthday_at_is_datetime_instance()
    {
        $this->assertInstanceOf(DateTime::class, $this->model->birthday_at);
    }
}
